export async function getServerSideProps({ res }) {
  const base = process.env.NEXT_PUBLIC_URL || 'https://topplistaguiden.vercel.app';
  const pages = [{"path":"","priority":"1.0","changefreq":"daily"},{"path":"/om-oss","priority":"0.5","changefreq":"monthly"},{"path":"/kontakt","priority":"0.4","changefreq":"monthly"},{"path":"/integritetspolicy","priority":"0.3","changefreq":"yearly"},{"path":"/robotdammsugare","priority":"0.8","changefreq":"weekly"},{"path":"/kaffemaskin","priority":"0.8","changefreq":"weekly"},{"path":"/luftrenare","priority":"0.8","changefreq":"weekly"},{"path":"/airfryer","priority":"0.8","changefreq":"weekly"},{"path":"/smarta-hem","priority":"0.8","changefreq":"weekly"},{"path":"/jamfor/philips-airfryer-xxl-hd9650-vs-ninja-foodi-dualzone-af300","priority":"0.7","changefreq":"weekly"},{"path":"/jamfor/philips-airfryer-xxl-hd9650-vs-tefal-actifry-genius-xl-ah9600","priority":"0.7","changefreq":"weekly"},{"path":"/jamfor/philips-airfryer-xxl-hd9650-vs-cosori-premium-cp158-af","priority":"0.7","changefreq":"weekly"},{"path":"/jamfor/philips-airfryer-xxl-hd9650-vs-instant-vortex-plus-6-in-1","priority":"0.7","changefreq":"weekly"},{"path":"/jamfor/philips-airfryer-xxl-hd9650-vs-delonghi-rotofry-f28311","priority":"0.7","changefreq":"weekly"},{"path":"/jamfor/philips-airfryer-xxl-hd9650-vs-breville-smart-oven-air-fryer","priority":"0.7","changefreq":"weekly"},{"path":"/jamfor/ninja-foodi-dualzone-af300-vs-tefal-actifry-genius-xl-ah9600","priority":"0.7","changefreq":"weekly"},{"path":"/jamfor/ninja-foodi-dualzone-af300-vs-cosori-premium-cp158-af","priority":"0.7","changefreq":"weekly"},{"path":"/jamfor/ninja-foodi-dualzone-af300-vs-instant-vortex-plus-6-in-1","priority":"0.7","changefreq":"weekly"},{"path":"/jamfor/ninja-foodi-dualzone-af300-vs-delonghi-rotofry-f28311","priority":"0.7","changefreq":"weekly"},{"path":"/jamfor/ninja-foodi-dualzone-af300-vs-breville-smart-oven-air-fryer","priority":"0.7","changefreq":"weekly"},{"path":"/jamfor/tefal-actifry-genius-xl-ah9600-vs-cosori-premium-cp158-af","priority":"0.7","changefreq":"weekly"},{"path":"/jamfor/tefal-actifry-genius-xl-ah9600-vs-instant-vortex-plus-6-in-1","priority":"0.7","changefreq":"weekly"},{"path":"/jamfor/tefal-actifry-genius-xl-ah9600-vs-delonghi-rotofry-f28311","priority":"0.7","changefreq":"weekly"},{"path":"/jamfor/tefal-actifry-genius-xl-ah9600-vs-breville-smart-oven-air-fryer","priority":"0.7","changefreq":"weekly"},{"path":"/jamfor/cosori-premium-cp158-af-vs-instant-vortex-plus-6-in-1","priority":"0.7","changefreq":"weekly"},{"path":"/jamfor/cosori-premium-cp158-af-vs-delonghi-rotofry-f28311","priority":"0.7","changefreq":"weekly"},{"path":"/jamfor/cosori-premium-cp158-af-vs-breville-smart-oven-air-fryer","priority":"0.7","changefreq":"weekly"},{"path":"/jamfor/instant-vortex-plus-6-in-1-vs-delonghi-rotofry-f28311","priority":"0.7","changefreq":"weekly"},{"path":"/jamfor/instant-vortex-plus-6-in-1-vs-breville-smart-oven-air-fryer","priority":"0.7","changefreq":"weekly"},{"path":"/jamfor/delonghi-rotofry-f28311-vs-breville-smart-oven-air-fryer","priority":"0.7","changefreq":"weekly"}];
  const xml = '<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">' +
    pages.map(function(p) { return '<url><loc>'+base+p.path+'</loc><lastmod>2026-06-24</lastmod><changefreq>'+p.changefreq+'</changefreq><priority>'+p.priority+'</priority></url>'; }).join('') +
    '</urlset>';
  res.setHeader('Content-Type', 'application/xml');
  res.setHeader('Cache-Control', 's-maxage=86400, stale-while-revalidate');
  res.write(xml); res.end();
  return { props: {} };
}
export default function Sitemap() { return null; }